name: Update Navigation Data

on:
  workflow_dispatch:
    inputs:
      navigationDataBase64:
        description: 'Base64 encoded navigation data (UTF-8 JSON)'
        required: true
        type: string
      commitMessage:
        description: 'Optional custom commit message'
        required: false
        type: string
      authorName:
        description: 'Optional git author name'
        required: false
        type: string
      authorEmail:
        description: 'Optional git author email'
        required: false
        type: string

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode navigation data
        id: decode
        env:
          NAVIGATION_DATA_BASE64: ${{ inputs.navigationDataBase64 }}
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');

          const base64 = process.env.NAVIGATION_DATA_BASE64 || '';
          if (!base64) {
            console.error('Missing navigation data input');
            process.exit(1);
          }

          let buffer;
          try {
            buffer = Buffer.from(base64, 'base64');
          } catch (error) {
            console.error('Invalid base64 payload');
            process.exit(1);
          }

          const jsonText = buffer.toString('utf8');
          let parsed;
          try {
            parsed = JSON.parse(jsonText);
          } catch (error) {
            console.error('Invalid JSON data:', error.message);
            process.exit(1);
          }

          const outputPath = path.join(process.cwd(), 'data', 'navigation.json');
          const formatted = JSON.stringify(parsed, null, 2);
          fs.writeFileSync(outputPath, formatted + '\n', 'utf8');
          NODE

      - name: Commit and push changes
        env:
          INPUT_COMMIT_MESSAGE: ${{ inputs.commitMessage }}
          INPUT_AUTHOR_NAME: ${{ inputs.authorName }}
          INPUT_AUTHOR_EMAIL: ${{ inputs.authorEmail }}
        run: |
          set -e

          AUTHOR_NAME="${INPUT_AUTHOR_NAME}"
          if [ -z "$AUTHOR_NAME" ]; then
            AUTHOR_NAME="SimPage Actions"
          fi

          AUTHOR_EMAIL="${INPUT_AUTHOR_EMAIL}"
          if [ -z "$AUTHOR_EMAIL" ]; then
            AUTHOR_EMAIL="actions@simpage.dev"
          fi

          COMMIT_MESSAGE="${INPUT_COMMIT_MESSAGE}"
          if [ -z "$COMMIT_MESSAGE" ]; then
            COMMIT_MESSAGE="Update navigation data via GitHub Actions"
          fi

          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"

          git add data/navigation.json

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "$COMMIT_MESSAGE"
          git push
